config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root             'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container-fluid">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	        </button>
	        <%= link_to "sample app", root_path, id: "logo", class: "navbar-brand" %>
	    </div>
	    <div class="navbar-collapse collapse">
	        <ul class="nav navbar-nav navbar-right">
	           	<li><%= link_to "Home", root_path %></li>
	            <li><%= link_to "Help", help_path %></li>
	            <% if signed_in? %>
	            	<li><%= link_to "Users", users_path %></li>
            		<li id="fat-menu" class="dropdown">
              			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                			Account <b class="caret"></b>
              			</a>
              			<ul class="dropdown-menu">
                			<li><%= link_to "Profile", current_user %></li>
                			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
                			<li class="divider"></li>
                			<li>
                  				<%= link_to "Sign out", signout_path, method: "delete" %>
                			</li>
              			</ul>
            		</li>
	            <% else %>
	            	<li><%= link_to "Sign in", signin_path %></li>
	            <% end %>
	        </ul>
	    </div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<!-- Static navbar -->
    <%= render 'layouts/header' %>

    <!-- Main component for a primary marketing message or call to action -->
    <div class="container">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>